# Numpy Practice 

### Do The following :
- Finish the practice
- share it on your github account

#### Write the code that will produce the requested output or action as you see on the following cell

In [9]:
## For example 
## to get the output Hello, Mohammed
print("Hello, Mohammed") ## TODO

Hello, Mohammed


In [1]:
print("Hello, my name is 'Faial'")

Hello, my name is 'Faial'


### import the package numpy and make the shortcut "np" for it. 

In [2]:
## TODO

!pip install numpy
import numpy as np

#### define a numpy array [1, 2, 3, 4, 5] and assign it to variable x 

In [3]:
## TODO

x = np.array([1,2,3,4,5])

### Print x 

In [4]:
## TODO 
print (x)

[1 2 3 4 5]


### Print the mean of x using numpy 

In [5]:
## TODO
print (f"The mean is: {x.mean()}")

The mean is: 3.0


### Print the maximum number in array x

In [7]:
## TODO 
print (f"The maximum is: {x.max()}")

The maximum is: 5


### Generate a random number between 35 and 40

In [10]:
## TODO 
#choose intger or float numbers
rand = np.random.default_rng()

#rand.random.uniform(35,40) # float

np.random.randint(35,40)  # int

35

### generate a list (N) of 1000 numbers with random values between 100 and 150  

In [11]:
## TODO 
#choose intger or float numbers 

# N = rand.random.uniform(low = 100, high = 150, size= 1000) # float

N = np.random.randint(100,150,size =(1000))                # int

N

array([132, 143, 104, 102, 106, 103, 142, 126, 117, 133, 141, 149, 141,
       112, 104, 135, 115, 140, 111, 113, 100, 116, 143, 122, 100, 114,
       104, 138, 102, 114, 141, 108, 136, 104, 139, 130, 116, 111, 111,
       143, 148, 136, 102, 115, 101, 135, 146, 101, 141, 141, 130, 138,
       102, 136, 140, 115, 126, 105, 113, 116, 140, 116, 133, 137, 142,
       139, 109, 145, 106, 127, 123, 143, 145, 125, 115, 104, 105, 128,
       128, 122, 121, 116, 124, 144, 131, 123, 136, 118, 142, 137, 137,
       120, 135, 142, 140, 141, 134, 124, 111, 109, 131, 125, 125, 145,
       141, 116, 143, 124, 132, 138, 143, 138, 115, 123, 143, 103, 102,
       135, 135, 133, 111, 148, 143, 146, 135, 133, 141, 147, 143, 147,
       145, 123, 101, 105, 137, 145, 133, 139, 134, 139, 142, 140, 128,
       101, 107, 114, 145, 127, 116, 125, 141, 108, 146, 109, 125, 146,
       111, 149, 120, 143, 100, 146, 149, 112, 134, 130, 111, 125, 146,
       102, 112, 104, 128, 140, 133, 135, 127, 111, 140, 135, 14

### get the mean, median, std, and variance of the list N 

In [12]:
## TODO 
print(f'The Mean is {np.mean(N)}')
print(f'The Median is {np.median(N)}')
print(f'The std is {np.std(N)}')
print(f'The variance is {np.var(N)}')

The Mean is 124.607
The Median is 124.0
The std is 14.568477991883709
The variance is 212.240551


### generate a 2D array of size 3 x 4 of random numbers between 18-65 

In [13]:
##TODO 
#choose intger or float numbers

ary1 = np.random.randint(18,65,size=(3,4)) #int

#ary1 = rng.uniform(low=18, high=65, size=(3,4)) #float

ary1

array([[36, 29, 26, 45],
       [42, 61, 34, 28],
       [50, 21, 57, 19]])

### Get the mean for every columns N

In [15]:
## TODO

colm = ary1.mean(axis = 0)
print(f'The First column {colm[0]}') 

print(f'The Second column {colm[1]}')

print(f'The Thered column {colm[2]}')

ary1

The First column 42.666666666666664
The Second column 37.0
The Thered column 39.0


array([[36, 29, 26, 45],
       [42, 61, 34, 28],
       [50, 21, 57, 19]])

### Get the mean for every row of N 


In [16]:
## TODO

Row = ary1.mean(axis = 1)
print(f'The First row  {Row[0]}') 

print(f'The Second row {Row[1]}')

print(f'The Thered row {Row[2]}')

ary1

The First row  34.0
The Second row 41.25
The Thered row 36.75


array([[36, 29, 26, 45],
       [42, 61, 34, 28],
       [50, 21, 57, 19]])

### Create the following 2D array (S) of students grade in a classroom
- grades [coursework, midterm exam, final exam]
- [20, 15, 40]
- [25, 24, 35]
- [21, 15, 25]

In [17]:
## TODO

S = np.array([[20, 15, 40],[25, 24, 35],[21, 15, 25],])

S

array([[20, 15, 40],
       [25, 24, 35],
       [21, 15, 25]])

### Get the sums of student grades in S

In [21]:
## TODO

mark = S.sum(axis = 1)

print('Stud1 =',mark[0])
print('Stud2 =',mark[1])
print('Stud3 =',mark[2])

Stud1 = 75
Stud2 = 84
Stud3 = 61


### Get the means of student grades in every activity (coursework, midterm exam, final exam) in S

In [22]:
## TODO

totalMarks = S.mean(axis = 0)

print(f"The Mean of Coursework {totalMarks[0]}")
print(f"The Mean of Midterm exam {totalMarks[1]}")
print(f"The Mean of Final exam {totalMarks[2]}")
S

The Mean of Coursework 22.0
The Mean of Midterm exam 18.0
The Mean of Final exam 33.333333333333336


array([[20, 15, 40],
       [25, 24, 35],
       [21, 15, 25]])

### reshape S in a way that make the colums represent the students and rows represent the activity, as follow
- [20, 25, 21] 
- [15, 24, 15]
- [40, 35, 25]

In [23]:
## TODO
trans = S.transpose()
#print("testoutput",b.mean(axis=1)[0])
#print("testoutput",b.mean(axis=1)[1])
#print("testoutput",b.mean(axis=1)[2])
trans

array([[20, 25, 21],
       [15, 24, 15],
       [40, 35, 25]])

# Pandas Practice 

### import the package pandas and make the shortcut "pd" for it. 

In [24]:
## TODO
!pip install pandas
import pandas as pd

### create Series call it (Data) with the values 'a','b','d','u' and 'I'

In [25]:
## TODO

data = ['a','b','d','u','I']
data

['a', 'b', 'd', 'u', 'I']

### change index to 3,6,9,12, and 15 for (data) 

In [27]:
## TODO

catalogue = [3,6,9,12,15]
pd.Series(data,catalogue)

3     a
6     b
9     d
12    u
15    I
dtype: object

### change index to client1, client2, client3, client4 and client5 for (data) 

In [32]:
## TODO 
pd.Series(data,index=['client1','client2','client3','client4','client5'])

client1    a
client2    b
client3    d
client4    u
client5    I
dtype: object

### create a dataframe (D) with the followin values
- 	Name -	Age
-   Ali	 -  55
- 	Ahmad -	15
- 	Nora -	40

### Get the means of ages of people in (D)

In [37]:
## TODO expected value is 36.66

names=['Ali','Ahmad','Nora']
ages = [55,15,40]
D = pd.DataFrame({'Name':names,'Age':ages})

D

Name  Age
0    Ali   55
1  Ahmad   15
2   Nora   40

In [39]:
np.mean(D)

Age    36.666667
dtype: float64